version: '2'
services:
  hawkbit:
    image: density/hawkbit:latest
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "15672:15672"